# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use `python setup.py update_constants` to update it.

MB_LANGUAGES = {
    u'aar': u'Afar',
    u'abk': u'Abkhazian',
    u'ace': u'Achinese',
    u'ach': u'Acoli',
    u'ada': u'Adangme',
    u'ady': u'Adyghe',
    u'afh': u'Afrihili',
    u'afr': u'Afrikaans',
    u'ain': u'Ainu',
    u'aka': u'Akan',
    u'ale': u'Aleut',
    u'alt': u'Southern Altai',
    u'amh': u'Amharic',
    u'ang': u'English, Old (ca.450-1100)',
    u'anp': u'Angika',
    u'ara': u'Arabic',
    u'arg': u'Aragonese',
    u'arn': u'Mapudungun',
    u'arp': u'Arapaho',
    u'arw': u'Arawak',
    u'asm': u'Assamese',
    u'ast': u'Asturian',
    u'ava': u'Avaric',
    u'ave': u'Avestan',
    u'awa': u'Awadhi',
    u'aym': u'Aymara',
    u'aze': u'Azerbaijani',
    u'bak': u'Bashkir',
    u'bal': u'Baluchi',
    u'bam': u'Bambara',
    u'ban': u'Balinese',
    u'bas': u'Basa',
    u'bej': u'Beja',
    u'bel': u'Belarusian',
    u'bem': u'Bemba',
    u'ben': u'Bengali',
    u'bho': u'Bhojpuri',
    u'bik': u'Bikol',
    u'bin': u'Bini',
    u'bis': u'Bislama',
    u'bla': u'Siksika',
    u'bod': u'Tibetan',
    u'bos': u'Bosnian',
    u'bra': u'Braj',
    u'bre': u'Breton',
    u'bua': u'Buriat',
    u'bug': u'Buginese',
    u'bul': u'Bulgarian',
    u'byn': u'Blin',
    u'cad': u'Caddo',
    u'car': u'Galibi Carib',
    u'cat': u'Catalan',
    u'ceb': u'Cebuano',
    u'ces': u'Czech',
    u'cha': u'Chamorro',
    u'chb': u'Chibcha',
    u'che': u'Chechen',
    u'chg': u'Chagatai',
    u'chk': u'Chuukese',
    u'chm': u'Mari',
    u'chn': u'Chinook jargon',
    u'cho': u'Choctaw',
    u'chp': u'Chipewyan',
    u'chr': u'Cherokee',
    u'chu': u'Church Slavic',
    u'chv': u'Chuvash',
    u'chy': u'Cheyenne',
    u'cmn': u'Mandarin Chinese',
    u'cop': u'Coptic',
    u'cor': u'Cornish',
    u'cos': u'Corsican',
    u'cre': u'Cree',
    u'crh': u'Crimean Tatar',
    u'csb': u'Kashubian',
    u'cym': u'Welsh',
    u'dak': u'Dakota',
    u'dan': u'Danish',
    u'dar': u'Dargwa',
    u'del': u'Delaware',
    u'den': u'Slave (Athapascan)',
    u'deu': u'German',
    u'dgr': u'Dogrib',
    u'din': u'Dinka',
    u'div': u'Divehi',
    u'doi': u'Dogri',
    u'dsb': u'Sorbian, Lower',
    u'dua': u'Duala',
    u'dum': u'Dutch, Middle (ca.1050-1350)',
    u'dyu': u'Dyula',
    u'dzo': u'Dzongkha',
    u'efi': u'Efik',
    u'eka': u'Ekajuk',
    u'ell': u'Greek',
    u'elx': u'Elamite',
    u'eng': u'English',
    u'enm': u'English, Middle (1100-1500)',
    u'epo': u'Esperanto',
    u'est': u'Estonian',
    u'eus': u'Basque',
    u'ewe': u'Ewe',
    u'ewo': u'Ewondo',
    u'fan': u'Fang',
    u'fao': u'Faroese',
    u'fas': u'Persian',
    u'fat': u'Fanti',
    u'fij': u'Fijian',
    u'fil': u'Filipino',
    u'fin': u'Finnish',
    u'fon': u'Fon',
    u'fra': u'French',
    u'fro': u'French, Old (842-ca.1400)',
    u'frr': u'Frisian, Northern',
    u'frs': u'Frisian, Eastern',
    u'fry': u'Frisian, Western',
    u'ful': u'Fulah',
    u'fur': u'Friulian',
    u'gaa': u'Ga',
    u'gay': u'Gayo',
    u'gba': u'Gbaya',
    u'gez': u'Geez',
    u'gil': u'Gilbertese',
    u'gla': u'Scottish Gaelic',
    u'gle': u'Irish',
    u'glg': u'Galician',
    u'glv': u'Manx',
    u'gmh': u'German, Middle High (ca.1050-1500)',
    u'gon': u'Gondi',
    u'gor': u'Gorontalo',
    u'got': u'Gothic',
    u'grb': u'Grebo',
    u'grc': u'Greek, Ancient',
    u'grn': u'Guarani',
    u'gsw': u'German, Swiss',
    u'guj': u'Gujarati',
    u'gwi': u'Gwich\'in',
    u'hai': u'Haida',
    u'hat': u'Haitian Creole',
    u'hau': u'Hausa',
    u'haw': u'Hawaiian',
    u'heb': u'Hebrew',
    u'her': u'Herero',
    u'hil': u'Hiligaynon',
    u'hin': u'Hindi',
    u'hmn': u'Hmong',
    u'hmo': u'Hiri Motu',
    u'hrv': u'Croatian',
    u'hsb': u'Sorbian, Upper',
    u'hun': u'Hungarian',
    u'hup': u'Hupa',
    u'hye': u'Armenian',
    u'iba': u'Iban',
    u'ibo': u'Igbo',
    u'ido': u'Ido',
    u'iii': u'Sichuan Yi',
    u'iku': u'Inuktitut',
    u'ile': u'Interlingue',
    u'ilo': u'Iloko',
    u'ina': u'Interlingua',
    u'ind': u'Indonesian',
    u'inh': u'Ingush',
    u'ipk': u'Inupiaq',
    u'isl': u'Icelandic',
    u'ita': u'Italian',
    u'izh': u'Ingrian',
    u'jam': u'Jamaican Creole English',
    u'jav': u'Javanese',
    u'jbo': u'Lojban',
    u'jpn': u'Japanese',
    u'jpr': u'Judeo-Persian',
    u'jrb': u'Judeo-Arabic',
    u'kaa': u'Kara-Kalpak',
    u'kab': u'Kabyle',
    u'kac': u'Kachin',
    u'kal': u'Greenlandic',
    u'kam': u'Kamba',
    u'kan': u'Kannada',
    u'kas': u'Kashmiri',
    u'kat': u'Georgian',
    u'kau': u'Kanuri',
    u'kaz': u'Kazakh',
    u'kbd': u'Kabardian',
    u'kca': u'Khanty',
    u'kha': u'Khasi',
    u'khm': u'Khmer, Central',
    u'kik': u'Kikuyu',
    u'kin': u'Kinyarwanda',
    u'kir': u'Kirghiz',
    u'kmb': u'Kimbundu',
    u'kok': u'Konkani',
    u'kom': u'Komi',
    u'kon': u'Kongo',
    u'kor': u'Korean',
    u'kos': u'Kosraean',
    u'kpe': u'Kpelle',
    u'krc': u'Karachay-Balkar',
    u'krl': u'Karelian',
    u'kru': u'Kurukh',
    u'ksh': u'Kölsch',
    u'kua': u'Kuanyama',
    u'kum': u'Kumyk',
    u'kur': u'Kurdish',
    u'kut': u'Kutenai',
    u'lad': u'Ladino',
    u'lah': u'Lahnda',
    u'lam': u'Lamba',
    u'lao': u'Lao',
    u'lat': u'Latin',
    u'lav': u'Latvian',
    u'lez': u'Lezghian',
    u'lim': u'Limburgish',
    u'lin': u'Lingala',
    u'lit': u'Lithuanian',
    u'liv': u'Liv',
    u'lkt': u'Lakota',
    u'lol': u'Mongo',
    u'loz': u'Lozi',
    u'ltz': u'Luxembourgish',
    u'lua': u'Luba-Lulua',
    u'lub': u'Luba-Katanga',
    u'lug': u'Ganda',
    u'lui': u'Luiseno',
    u'lun': u'Lunda',
    u'luo': u'Luo',
    u'lus': u'Lushai',
    u'mad': u'Madurese',
    u'mag': u'Magahi',
    u'mah': u'Marshallese',
    u'mai': u'Maithili',
    u'mak': u'Makasar',
    u'mal': u'Malayalam',
    u'man': u'Mandingo',
    u'mar': u'Marathi',
    u'mas': u'Masai',
    u'mdf': u'Moksha',
    u'mdr': u'Mandar',
    u'men': u'Mende',
    u'mic': u'Mi\'kmaq',
    u'min': u'Minangkabau',
    u'mkd': u'Macedonian',
    u'mlg': u'Malagasy',
    u'mlt': u'Maltese',
    u'mnc': u'Manchu',
    u'mni': u'Manipuri',
    u'mns': u'Mansi',
    u'moe': u'Montagnais',
    u'moh': u'Mohawk',
    u'mon': u'Mongolian',
    u'mos': u'Mossi',
    u'mri': u'Maori',
    u'msa': u'Malay',
    u'mul': u'[Multiple languages]',
    u'mus': u'Creek',
    u'mwl': u'Mirandese',
    u'mwr': u'Marwari',
    u'mya': u'Burmese',
    u'myv': u'Erzya',
    u'nan': u'Min Nan Chinese',
    u'nap': u'Neapolitan',
    u'nau': u'Nauru',
    u'nav': u'Navajo',
    u'nbl': u'Ndebele, South',
    u'nde': u'Ndebele, North',
    u'ndo': u'Ndonga',
    u'nds': u'German, Low',
    u'nep': u'Nepali',
    u'new': u'Nepal Bhasa',
    u'nia': u'Nias',
    u'niu': u'Niuean',
    u'nld': u'Dutch',
    u'nno': u'Norwegian Nynorsk',
    u'nob': u'Norwegian Bokmål',
    u'nog': u'Nogai',
    u'non': u'Norse, Old',
    u'nor': u'Norwegian',
    u'nqo': u'N\'Ko',
    u'nso': u'Sotho, Northern',
    u'nya': u'Chichewa',
    u'nym': u'Nyamwezi',
    u'nyn': u'Nyankole',
    u'nyo': u'Nyoro',
    u'nzi': u'Nzima',
    u'oci': u'Occitan',
    u'oji': u'Ojibwa',
    u'ori': u'Oriya',
    u'orm': u'Oromo',
    u'osa': u'Osage',
    u'oss': u'Ossetian',
    u'ota': u'Turkish, Ottoman',
    u'pag': u'Pangasinan',
    u'pam': u'Pampanga',
    u'pan': u'Panjabi',
    u'pap': u'Papiamento',
    u'pau': u'Palauan',
    u'pli': u'Pali',
    u'pol': u'Polish',
    u'pon': u'Pohnpeian',
    u'por': u'Portuguese',
    u'pus': u'Pushto',
    u'pyu': u'Puyuma',
    u'qaa': u'[Artificial (Other)]',
    u'que': u'Quechua',
    u'qya': u'Quenya',
    u'raj': u'Rajasthani',
    u'rap': u'Rapanui',
    u'rar': u'Rarotongan',
    u'rcf': u'Réunion Creole French',
    u'roh': u'Romansh',
    u'rom': u'Romany',
    u'ron': u'Romanian',
    u'run': u'Rundi',
    u'rup': u'Aromanian',
    u'rus': u'Russian',
    u'rys': u'Yaeyama',
    u'ryu': u'Central Okinawan',
    u'sad': u'Sandawe',
    u'sag': u'Sango',
    u'sah': u'Yakut',
    u'sam': u'Samaritan Aramaic',
    u'san': u'Sanskrit',
    u'sas': u'Sasak',
    u'sat': u'Santali',
    u'scn': u'Sicilian',
    u'sco': u'Scots',
    u'sel': u'Selkup',
    u'shn': u'Shan',
    u'sid': u'Sidamo',
    u'sin': u'Sinhala',
    u'sjn': u'Sindarin',
    u'slk': u'Slovak',
    u'slv': u'Slovenian',
    u'sma': u'Sami, Southern',
    u'sme': u'Sami, Northern',
    u'smj': u'Sami, Lule',
    u'smn': u'Sami, Inari',
    u'smo': u'Samoan',
    u'sms': u'Sami, Skolt',
    u'sna': u'Shona',
    u'snd': u'Sindhi',
    u'snk': u'Soninke',
    u'som': u'Somali',
    u'sot': u'Sotho, Southern',
    u'spa': u'Spanish',
    u'sqi': u'Albanian',
    u'srd': u'Sardinian',
    u'srn': u'Sranan Tongo',
    u'srp': u'Serbian',
    u'srr': u'Serer',
    u'ssw': u'Swati',
    u'suk': u'Sukuma',
    u'sun': u'Sundanese',
    u'sus': u'Susu',
    u'swa': u'Swahili',
    u'swe': u'Swedish',
    u'syr': u'Syriac',
    u'tah': u'Tahitian',
    u'tam': u'Tamil',
    u'tat': u'Tatar',
    u'tel': u'Telugu',
    u'tem': u'Timne',
    u'ter': u'Tereno',
    u'tet': u'Tetum',
    u'tgk': u'Tajik',
    u'tgl': u'Tagalog',
    u'tha': u'Thai',
    u'tig': u'Tigre',
    u'tir': u'Tigrinya',
    u'tiv': u'Tiv',
    u'tkl': u'Tokelau',
    u'tlh': u'Klingon',
    u'tli': u'Tlingit',
    u'tmh': u'Tamashek',
    u'tog': u'Tonga (Nyasa)',
    u'ton': u'Tonga (Tonga Islands)',
    u'tpi': u'Tok Pisin',
    u'tsi': u'Tsimshian',
    u'tsn': u'Tswana',
    u'tso': u'Tsonga',
    u'tuk': u'Turkmen',
    u'tum': u'Tumbuka',
    u'tur': u'Turkish',
    u'tvl': u'Tuvalu',
    u'twi': u'Twi',
    u'tyv': u'Tuvinian',
    u'udm': u'Udmurt',
    u'uig': u'Uighur',
    u'ukr': u'Ukrainian',
    u'umb': u'Umbundu',
    u'urd': u'Urdu',
    u'uzb': u'Uzbek',
    u'vai': u'Vai',
    u'ven': u'Venda',
    u'vep': u'Veps',
    u'vie': u'Vietnamese',
    u'vol': u'Volapük',
    u'vot': u'Votic',
    u'vro': u'Võro',
    u'wal': u'Wolaitta',
    u'war': u'Waray',
    u'was': u'Washo',
    u'wln': u'Walloon',
    u'wol': u'Wolof',
    u'xal': u'Kalmyk',
    u'xce': u'Celtiberian',
    u'xho': u'Xhosa',
    u'yao': u'Yao',
    u'yap': u'Yapese',
    u'yid': u'Yiddish',
    u'yor': u'Yoruba',
    u'yue': u'Yue Chinese',
    u'zap': u'Zapotec',
    u'zen': u'Zenaga',
    u'zha': u'Zhuang',
    u'zho': u'Chinese',
    u'zul': u'Zulu',
    u'zun': u'Zuni',
    u'zxx': u'No linguistic content',
    u'zza': u'Zaza',
}
