# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use `python setup.py update_constants` to update it.

MB_SCRIPTS = {
    u'Afak': u'Afaka',
    u'Arab': u'Arabic',
    u'Armi': u'Imperial Aramaic',
    u'Armn': u'Armenian',
    u'Avst': u'Avestan',
    u'Bali': u'Balinese',
    u'Bamu': u'Bamum',
    u'Bass': u'Bassa Vah',
    u'Batk': u'Batak',
    u'Beng': u'Bengali',
    u'Blis': u'Blissymbols',
    u'Bopo': u'Bopomofo',
    u'Brah': u'Brahmi',
    u'Brai': u'Braille',
    u'Bugi': u'Buginese',
    u'Buhd': u'Buhid',
    u'Cakm': u'Chakma',
    u'Cans': u'Canadian Syllabics',
    u'Cari': u'Carian',
    u'Cham': u'Cham',
    u'Cher': u'Cherokee',
    u'Cirt': u'Cirth',
    u'Copt': u'Coptic',
    u'Cprt': u'Cypriot',
    u'Cyrl': u'Cyrillic',
    u'Cyrs': u'Cyrillic (Old Church Slavonic variant)',
    u'Deva': u'Devanagari',
    u'Dsrt': u'Deseret',
    u'Dupl': u'Duployan shorthand',
    u'Egyd': u'Egyptian demotic',
    u'Egyh': u'Egyptian hieratic',
    u'Egyp': u'Egyptian hieroglyphs',
    u'Elba': u'Elbasan',
    u'Ethi': u'Ethiopic',
    u'Geok': u'Khutsuri',
    u'Geor': u'Georgian',
    u'Glag': u'Glagolitic',
    u'Goth': u'Gothic',
    u'Gran': u'Grantha',
    u'Grek': u'Greek',
    u'Gujr': u'Gujarati',
    u'Guru': u'Gurmukhi',
    u'Hang': u'Hangul',
    u'Hani': u'Han (Hanzi, Kanji, Hanja)',
    u'Hano': u'Hanunoo',
    u'Hans': u'Han (Simplified variant)',
    u'Hant': u'Han (Traditional variant)',
    u'Hebr': u'Hebrew',
    u'Hira': u'Hiragana',
    u'Hmng': u'Pahawh Hmong',
    u'Hrkt': u'Japanese syllabaries',
    u'Hung': u'Old Hungarian',
    u'Inds': u'Indus',
    u'Ital': u'Old Italic',
    u'Java': u'Javanese',
    u'Jpan': u'Japanese',
    u'Jurc': u'Jurchen',
    u'Kali': u'Kayah Li',
    u'Kana': u'Katakana',
    u'Khar': u'Kharoshthi',
    u'Khmr': u'Khmer',
    u'Khoj': u'Khojki',
    u'Knda': u'Kannada',
    u'Kore': u'Korean',
    u'Kpel': u'Kpelle',
    u'Kthi': u'Kaithi',
    u'Lana': u'Tai Tham',
    u'Laoo': u'Lao',
    u'Latf': u'Latin (Fraktur variant)',
    u'Latg': u'Latin (Gaelic variant)',
    u'Latn': u'Latin',
    u'Lepc': u'Lepcha',
    u'Limb': u'Limbu',
    u'Lina': u'Linear A',
    u'Linb': u'Linear B',
    u'Lisu': u'Lisu (Fraser)',
    u'Loma': u'Loma',
    u'Lyci': u'Lycian',
    u'Lydi': u'Lydian',
    u'Mand': u'Mandaic',
    u'Mani': u'Manichaean',
    u'Maya': u'Mayan hieroglyphs',
    u'Mend': u'Mende',
    u'Merc': u'Meroitic Cursive',
    u'Mero': u'Meroitic Hieroglyphs',
    u'Mlym': u'Malayalam',
    u'Mong': u'Mongolian',
    u'Moon': u'Moon',
    u'Mroo': u'Mro, Mru',
    u'Mtei': u'Meitei Mayek',
    u'Mymr': u'Myanmar',
    u'Narb': u'Old North Arabian',
    u'Nbat': u'Nabataean',
    u'Nkgb': u'Nakhi Geba',
    u'Nkoo': u'N\'ko',
    u'Nshu': u'Nüshu',
    u'Ogam': u'Ogham',
    u'Olck': u'Ol Chiki',
    u'Orkh': u'Old Turkish',
    u'Orya': u'Oriya',
    u'Osma': u'Osmanya',
    u'Palm': u'Palmyrene',
    u'Perm': u'Old Permic',
    u'Phag': u'Phags-pa',
    u'Phli': u'Inscriptional Pahlavi',
    u'Phlp': u'Psalter Pahlavi',
    u'Phlv': u'Book Pahlavi',
    u'Phnx': u'Phoenician',
    u'Plrd': u'Miao',
    u'Prti': u'Inscriptional Parthian',
    u'Qaaa': u'[Multiple scripts]',
    u'Rjng': u'Rejang',
    u'Roro': u'Rongorongo',
    u'Runr': u'Runic',
    u'Samr': u'Samaritan',
    u'Sara': u'Sarati',
    u'Sarb': u'Old South Arabian',
    u'Saur': u'Saurashtra',
    u'Sgnw': u'SignWriting',
    u'Shaw': u'Shavian',
    u'Shrd': u'Sharada',
    u'Sind': u'Khudawadi',
    u'Sinh': u'Sinhala',
    u'Sora': u'Sora Sompeng',
    u'Sund': u'Sundanese',
    u'Sylo': u'Syloti Nagri',
    u'Syrc': u'Syriac',
    u'Syre': u'Syriac (Estrangelo variant)',
    u'Syrj': u'Syriac (Western variant)',
    u'Syrn': u'Syriac (Eastern variant)',
    u'Tagb': u'Tagbanwa',
    u'Takr': u'Takri',
    u'Tale': u'Tai Le',
    u'Talu': u'New Tai Lue',
    u'Taml': u'Tamil',
    u'Tang': u'Tangut',
    u'Tavt': u'Tai Viet',
    u'Telu': u'Telugu',
    u'Teng': u'Tengwar',
    u'Tfng': u'Tifinagh',
    u'Tglg': u'Tagalog',
    u'Thaa': u'Thaana',
    u'Thai': u'Thai',
    u'Tibt': u'Tibetan',
    u'Tirh': u'Tiruta',
    u'Ugar': u'Ugaritic',
    u'Vaii': u'Vai',
    u'Visp': u'Visible Speech',
    u'Wara': u'Warang Citi',
    u'Wole': u'Woleai',
    u'Xpeo': u'Old Persian',
    u'Xsux': u'Cuneiform, Sumero-Akkadian',
    u'Yiii': u'Yi',
    u'Zinh': u'Code for inherited script',
    u'Zmth': u'Mathematical notation',
    u'Zsym': u'Symbols',
    u'Zxxx': u'Code for unwritten documents',
    u'Zyyy': u'Code for undetermined script',
    u'Zzzz': u'Code for uncoded script',
}
