# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use `python setup.py update_constants` to update it.

MB_SCRIPTS = {
    u'Arab': u'Arabic',
    u'Armn': u'Armenian',
    u'Bali': u'Balinese',
    u'Beng': u'Bengali',
    u'Bopo': u'Bopomofo',
    u'Bugi': u'Buginese',
    u'Buhd': u'Buhid',
    u'Cans': u'Canadian Syllabics',
    u'Cari': u'Carian',
    u'Cham': u'Cham',
    u'Cher': u'Cherokee',
    u'Copt': u'Coptic',
    u'Cprt': u'Cypriot',
    u'Cyrl': u'Cyrillic',
    u'Deva': u'Devanagari',
    u'Dsrt': u'Deseret',
    u'Ethi': u'Ethiopic',
    u'Geok': u'Khutsuri',
    u'Geor': u'Georgian',
    u'Glag': u'Glagolitic',
    u'Goth': u'Gothic',
    u'Grek': u'Greek',
    u'Gujr': u'Gujarati',
    u'Guru': u'Gurmukhi',
    u'Hang': u'Hangul',
    u'Hani': u'Han (Hanzi, Kanji, Hanja)',
    u'Hano': u'Hanunoo',
    u'Hans': u'Han (Simplified variant)',
    u'Hant': u'Han (Traditional variant)',
    u'Hebr': u'Hebrew',
    u'Hira': u'Hiragana',
    u'Hrkt': u'Japanese syllabaries',
    u'Ital': u'Old Italic',
    u'Jpan': u'Japanese',
    u'Kali': u'Kayah Li',
    u'Kana': u'Katakana',
    u'Khar': u'Kharoshthi',
    u'Khmr': u'Khmer',
    u'Knda': u'Kannada',
    u'Kore': u'Korean',
    u'Laoo': u'Lao',
    u'Latn': u'Latin',
    u'Lepc': u'Lepcha',
    u'Limb': u'Limbu',
    u'Linb': u'Linear B',
    u'Lyci': u'Lycian',
    u'Lydi': u'Lydian',
    u'Mlym': u'Malayalam',
    u'Mong': u'Mongolian',
    u'Mymr': u'Myanmar',
    u'Nkoo': u'N\'ko',
    u'Ogam': u'Ogham',
    u'Olck': u'Ol Chiki',
    u'Orya': u'Oriya',
    u'Osma': u'Osmanya',
    u'Phag': u'Phags-pa',
    u'Phnx': u'Phoenician',
    u'Qaaa': u'[Multiple scripts]',
    u'Rjng': u'Rejang',
    u'Runr': u'Runic',
    u'Saur': u'Saurashtra',
    u'Shaw': u'Shavian',
    u'Sinh': u'Sinhala',
    u'Sund': u'Sundanese',
    u'Sylo': u'Syloti Nagri',
    u'Syrc': u'Syriac',
    u'Tagb': u'Tagbanwa',
    u'Tale': u'Tai Le',
    u'Talu': u'New Tai Lue',
    u'Taml': u'Tamil',
    u'Telu': u'Telugu',
    u'Tfng': u'Tifinagh',
    u'Tglg': u'Tagalog',
    u'Thaa': u'Thaana',
    u'Thai': u'Thai',
    u'Tibt': u'Tibetan',
    u'Ugar': u'Ugaritic',
    u'Vaii': u'Vai',
    u'Xpeo': u'Old Persian',
    u'Xsux': u'Cuneiform, Sumero-Akkadian',
    u'Yiii': u'Yi',
    u'Zmth': u'Mathematical notation',
    u'Zsym': u'Symbols',
}
